### ISSUE TITLE
Unable to connect to Galaxy Node

### ISSUE THREAD

**Issue by roman2810** [wwsupport/GalaxyBackup#1]
When I try to use the tool, at the moment it tries to connect to GR node the process is canceled and SMC console reports the following two alarms:
![4178d5a8-1ca2-44b7-88aa-fac58738a098](https://github.com/wwsupport/GalaxyBackup/assets/57016549/7a55d985-c8ea-4256-86e1-f456ace7ddca)
![9a187eaf-73f5-4a9b-b436-5bc80386a652](https://github.com/wwsupport/GalaxyBackup/assets/57016549/6079150e-e341-4454-b41e-2cb546ee44ab)

As additional details, there are 2 VMs. One carries GR, another is a developer station and carries IDE on it. The tool is started from engineering station to get galaxy from GR node and store it in local folder on engineering station.

Could you please advise how to fix that?

**Comment by Tazarelen** [comment]
What command are you using? And have you tried running it on the GR?

**Comment by roman2810** [comment]
Issue was solved. Instead of this one, I recompiled the original Galaxy Backup tool for .Net 4.7 and new GRAccess library. Those tool worked fine for me.

**Comment by Tazarelen** [comment]
Can you upload the executable? I seem to have an older version.

**Comment by roman2810** [comment]
[Galaxy Backup Tool.zip](https://github.com/wwsupport/GalaxyBackup/files/12036533/Galaxy.Backup.Tool.zip)

Here. 
In comparison to what was in your build, here galaxy login part is implemented as well, through corresponding method. 
Hope it will be helpfull.

**Comment by Tazarelen** [comment]
Seems to work great. Thanks a lot. This tool is excellent for making automated backup of our galaxies.

I guess there is different ways of using this tool. I am using a batch-script that adds time and date to the filename, and then I run this from Task Scheduler every night. When I need to input username and password when running the command, I need to input it in the bat-file, and that is less secure. Also I can see that in smc under flag info and component Galaxy Backup it actually showed my whole command line including username and password. It would also be more secure if that did not happen.

My dream for the tool would be that it checked for changes in the galaxy and only made the new cab file if there has been anything change since last backup was taken.

**Comment by roman2810** [comment]
We used this tool basically in the same way, using bat-files and task scheduler. Agree, in terms of security, it's not at all. 
First thing, which comes to my mind and I did it through PowerShell script file, the credentials could be supplied in encrypted way. Not sure how to make similar thing with bat-file. 
As for full command text in SMC console log during execution, agree it's not too secure as well, but really good to have for troubleshooting. What we potentially could do here is to implement a new parameter with log message level like: info, error, warn, debug. And depending on the value, supplied to this parameter during execution send or not this message to log file.

As for the last one, sounds interesting. I wonder is there any method in Aveva libraries, which can check differences?

**Comment by Tazarelen** [comment]
I agree that it is great that it is being logged to smc for troubleshooting. So either we should be able to turn that kind of logging off when running the utility, or it should be logged to a different flag that is not usually on.

I do not know so much about programming and the aveva libraries, but from time to time I use a sql script to find out if there has been any changes in the Galaxy.
